test_queries = [
    # vague
    "How can I order a washing machine through the cafeteria plan?",
    "How much is the Family Allowance for my third child?",
    "I lost my company credit card, what should I do?",
    "When are the weekly team lunches?",
    "How does the Two-Factor-Athentication for Facebook work?",
    "Why do I need a Criminal Record Extract to use the Cafeteria Plan?",
    "Whats the password for the DTSC Netflix Account?",
    "What's my salary if I work 20 hours a week?",
    "Why do I need a Criminal Record Extract to use the company credit card?",
    "What is Marco's job description?",
    "How many leave days can I take?",
    "Can I get government subsidies for learning dutch?",
    "Which exact amounts appear in the mobility reimbursement policy?",
    "What financial documentation is needed when using BNP?",
    "I have a friend that might be suitable to join the DTSC team, what should I do?",
    "Are there cases in which the maternity leave cannot be granted?",
    "What are the company's time-tracking policies?",
    "What car models are there to choose from?",
    "Can you help me prepare my TED talk?",
    "Can the Belgian government grant me agricultural subsidies?",
    # concrete
    "How to activate Music Streaming?",
    "What's the BeCentral address?",
    "What is the printing code?",
    "What is the password for StaffIT?",
    "Whats the Securex Insurance Policy Number?",
    "How can I track website performance?",
    "On which days do we post on LinkedIn?",
    "Who is responsible in case of a traffic fine?",
    "Is it difficult to get EU subsidies?",
    "How do I reserve a room at BeCentral?",
    "Who can create a new page on dtsc.be?",
    "How can I share concerns with my boss or other employees?",
    "What is DTSCoworking",
    "How long is the maternity leave?",
    "How long is the Microsoft Authenticator Code?",
    "What is the login information for Elia?",
    "What is Catherine Lefrancs phone number?",
    "Is there a Gym Membership in the Cafeteria Plan?",
    "When do I receive the Cafeteria Plan document?",
    "What's the contact e-mail for fleet assistance?"
]