question_list = [
    "What are the cafeteria plan benefits?",
    "Quels sont les avantages du plan cafétéria ?",
    "Wat zijn de voordelen van het cafetariaplan?",
    "Was sind die Vorteile des Cafeteria-Plans?",
    "What about my car configuration offer?",
    "Qu'en est-il de mon offre de configuration de voiture ?",
    "Hoe zit het met mijn autoconfiguratieaanbod?",
    "Was ist mit meinem Autokonfigurationsangebot?",
    "What about Connecting Expertise?",
    "Qu'en est-il de Connecting Expertise ?",
    "Hoe zit het met Connecting Expertise?",
    "Was ist mit Connecting Expertise?",
    "What's the BeCentral address?",
    "Quelle est l'adresse de BeCentral ?",
    "Wat is het adres van BeCentral?",
    "Wie lautet die Adresse von BeCentral?",
    "How to modify a page on dtsc.be?",
    "Comment modifier une page sur dtsc.be ?",
    "Hoe wijzig ik een pagina op dtsc.be?",
    "Wie kann ich eine Seite auf dtsc.be ändern?",
    "What are compensatory rest days?",
    "Que sont les jours de repos compensatoire ?",
    "Wat zijn compensatierustdagen?",
    "Was sind Ausgleichsruhetage?",
    "How do I access the shared library on the SharePoint?",
    "Comment accéder à la bibliothèque partagée sur SharePoint ?",
    "Hoe krijg ik toegang tot de gedeelde bibliotheek op SharePoint?",
    "Wie greife ich auf die gemeinsame Bibliothek auf SharePoint zu?",
    "What is the login for StaffIT?",
    "Quel est l'identifiant pour StaffIT ?",
    "Wat is de login voor StaffIT?",
    "Was ist der Login für StaffIT?",
    "How can I export leads from Odoo?",
    "Comment puis-je exporter des prospects depuis Odoo ?",
    "Hoe kan ik leads exporteren uit Odoo?",
    "Wie kann ich Leads aus Odoo exportieren?",
    "What is the structure for OneDrive?",
    "Quelle est la structure pour OneDrive ?",
    "Wat is de structuur voor OneDrive?",
    "Wie ist die Struktur für OneDrive?",
    "Who is responsible in case of a traffic fine?",
    "Qui est responsable en cas d'amende routière ?",
    "Wie is verantwoordelijk in geval van een verkeersboete?",
    "Wer ist bei einem Verkehrsbußgeld verantwortlich?",
    "Can I contact the CEO a green card?",
    "Puis-je contacter le PDG avec une carte verte ?",
    "Kan ik de CEO een groene kaart sturen?",
    "Kann ich dem CEO eine grüne Karte zukommen lassen?",
    "What about the company credit card?",
    "Qu'en est-il de la carte de crédit de l'entreprise ?",
    "Hoe zit het met de bedrijfscreditcard?",
    "Was ist mit der Firmenkreditkarte?",
    "What about Supplementary Family Allowances?",
    "Qu'en est-il des allocations familiales supplémentaires ?",
    "Hoe zit het met aanvullende kinderbijslag?",
    "Was ist mit dem zusätzlichen Kindergeld?",
    "What activities are included in the DTeam Spirit Challenge?",
    "Quelles activités sont incluses dans le DTeam Spirit Challenge ?",
    "Welke activiteiten zijn inbegrepen in de DTeam Spirit Challenge?",
    "Welche Aktivitäten sind in der DTeam Spirit Challenge enthalten?",
    "What are the limits for the mobility budget?",
    "Quelles sont les limites du budget mobilité ?",
    "Wat zijn de limieten voor het mobiliteitsbudget?",
    "Was sind die Grenzen für das Mobilitätsbudget?",
    "What about birth leave?",
    "Qu'en est-il du congé de naissance ?",
    "Hoe zit het met geboorteverlof?",
    "Was ist mit dem Geburtsurlaub?",
    "How to activate Music Streaming?",
    "Comment activer le streaming musical ?",
    "Hoe activeer ik muziekstreaming?",
    "Wie aktiviere ich Musik-Streaming?",
    "What is Scrum for?",
    "À quoi sert Scrum ?",
    "Waar dient Scrum voor?",
    "Wofür ist Scrum gedacht?",
    "Best practices for linkedin according to David's BB project?",
    "Meilleures pratiques pour LinkedIn selon le projet BB de David ?",
    "Beste praktijken voor LinkedIn volgens Davids BB-project?",
    "Best Practices für LinkedIn laut Davids BB-Projekt?"
]